---
abstract: 'Simple, clean handing of named/keyword arguments.'
author:
  - 'Paul Driver <frodwith@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102345, CPAN::Meta::Converter version 2.101600'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Kwargs
requires:
  Sub::Exporter: 0
version: 0.01
